appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a83aeb3c070044c6b1
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: T5QXlH0PhvgVEL21QGQWp7JDIgL6Kv/A7XaewIbTlY2HOJiCRoXJSrxpMl5fzB6ea8hJ0SHnXeSGGIxM/z9p1rLKIjbKrKsdCUZTwGZqhp7VEoUydofvunkZyc3TBZHGiHyO58VDsnT7z47bSOAOwiHAX3syPBxsVvDiQYJdN0Wb+rFyqP/1XefqEO+pV5BOVynCoUltS+LzOFhhOpjiZh3lmf6s0aWjaL4+RwFWI9Ptsmj/qRN/SLa5ErsPPgfv6YZKFj6HEhOv0eHpJ5HHdf4XtoRcfPwuc9Q4EHfZC/sU7t/Uny+sHTLm2M5PZVtOIBCLsyUohrfPgYgmkIk0DAmhu2L189B87FjcrX49XQcSsUI36jtXODL2fkvS7L9Lgd9Pz+7boRMnTrO6UbKDYeAb5B/G9dD25BxXL2cyQ2PqEqbaO/twoqxhzYW7Kmt21p7HHJUz5HOQOlSj0jUi6m+J/6sq+oiH6846+tfiX2IT+AVezXVFCj+ay090ZZXo5VN0TILa5qmvEd0IwHJY1SCaKANGJpLFrq4/VDjaYGNF/zIi714yFaVwHHG3pdsF/mu0ugqeoA4NOGA32/XKwXvgDCzgVHyHyo5M9oOlpeqAnQAlONggQ1pDUwZ1YGDFaKypagetWRZD6loeJihiAzshyjZZ/SX/j1Hs79TmRmM=}
